
services:
  backend:
    build:
      context: ./portfolio-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/portfolio
  frontend:
    build:
      context: ./portfolio-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo:
    restart: always
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"

  
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    hostname: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
