# Common Configuration
frontend:
#  url: http://localhost:3000
  url: https://portfolio-delta-nine-15.vercel.app/

backend:
  url: http://localhost:8080

website:
  domain: localhost

spring:
  data:
    mongodb:
      uri: mongodb+srv://igouriny:ilyassdbadmin123!@portfolio.4dznz.mongodb.net/portfolio?retryWrites=true&w=majority&appName=portfolio
#      uri: mongodb://mongo:27017/portfolio
      auto-index-creation: true


server:
  port: 8080

  error:
    include-message: always

logging:
  level:
    root: INFO
    com.gouriny: DEBUG

---
# Test Configuration
spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      username: root
      password: password
      host: mongo
      port: 27017
      database: portfolio
      authentication-database: admin
      auto-index-creation: true


de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

